In [16]:
from combinations_orthogonal_poly import orthogonal_polynomial
import numpy as np
import glob
import os

In [7]:
np.load("site_0-1.csv.npy")

array([[[[    0.        ,     0.        ,     0.        ,
              0.        ],
         [    0.        ,     0.        ,     0.        ,
              0.        ],
         [    0.        ,     0.        ,     0.        ,
              0.        ],
         [    0.        ,     0.        ,     0.        ,
              0.        ]],

        [[-1034.08004744, -8693.04119251,  1930.20215642,
          -8693.04119252],
         [    0.        ,     0.        ,     0.        ,
              0.        ],
         [    0.        ,     0.        ,     0.        ,
              0.        ],
         [ 1249.09336739,     0.        , -1249.09336739,
              0.        ]]],


       [[[-1034.08004744,     0.        ,     0.        ,
           1249.09336739],
         [-8693.04119251,     0.        ,     0.        ,
              0.        ],
         [ 1930.20215642,     0.        ,     0.        ,
          -1249.09336739],
         [-8693.04119252,     0.        ,     0.        ,
 

In [62]:
np.load("site_36-38.csv.npy")

array([[[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00]],

        [[ 2.79642509e+03, -3.69625923e+03,  2.75932132e+02,
          -1.30862503e+03],
         [-2.46956739e+03,  1.05122872e+04, -1.41110267e+03,
          -1.39070283e+03],
         [ 2.70471262e+03, -1.25354686e+04,  1.62689861e+03,
           3.45785717e+03],
         [-4.85806052e+03,  1.14934392e+04,  2.35771863e+00,
          -3.00034139e+03]]],


       [[[ 2.79642509e+03, -2.46956739e+03,  2.70471262e+03,
          -4.85806052e+03],
         [-3.69625923e+03,  1.05122872e+04, -1.25354686e+04,
           1.14934392e+04],
         [ 2.75932132e+02, -1.41110267e+03,  1.62689861e+03,
           2.35771863e+00],
         [-1.30

In [61]:
orthogonal_polynomial('/Users/saba.nafees/Desktop/STAR/ortho_seqs/two_combinations_data/site_0-1.csv', sites=2, dm=4, N=99)

mean
Regression of trait on site 1
[[ 1653.07877889     0.             0.         -1653.07877889]
 [-1252.14501213  -332.32560955 -1379.11459963  6639.59084799]]
Regression of trait on site 2
[[[[    0.             0.             0.             0.        ]
   [    0.             0.             0.             0.        ]
   [    0.             0.             0.             0.        ]
   [    0.             0.             0.             0.        ]]

  [[-1034.08004744 -8693.04119251  1930.20215642 -8693.04119252]
   [    0.             0.             0.             0.        ]
   [    0.             0.             0.             0.        ]
   [ 1249.09336739     0.         -1249.09336739     0.        ]]]


 [[[-1034.08004744     0.             0.          1249.09336739]
   [-8693.04119251     0.             0.             0.        ]
   [ 1930.20215642     0.             0.         -1249.09336739]
   [-8693.04119252     0.             0.             0.        ]]

  [[    0.          

In [36]:
folder = '/Users/saba.nafees/Desktop/STAR/ortho_seqs/two_combinations_data/'

In [37]:
!ls -lha $folder

total 6240
drwxr-xr-x  782 saba.nafees  staff    24K Mar  4 23:32 .
drwxr-xr-x   19 saba.nafees  staff   608B Mar  5 16:30 ..
-rw-r--r--@   1 saba.nafees  staff   297B Mar  4 23:22 site_0-1.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_0-10.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_0-11.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_0-12.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_0-13.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_0-14.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_0-15.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_0-16.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_0-17.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_0-18.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_0-19.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_0-2.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4

-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_17-31.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_17-32.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_17-33.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_17-34.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_17-35.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_17-36.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_17-37.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_17-38.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_17-39.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_18-19.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_18-20.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_18-21.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_18-22.csv
-rw-r--r--    1 saba.nafees  staff   297B Mar  4 23:22 site_18-23.csv
-rw-r--r--    1 saba

In [41]:
for filename in os.listdir(folder):
    print(filename)

site_36-38.csv
site_10-28.csv
site_17-21.csv
site_5-11.csv
site_17-35.csv
site_2-18.csv
site_10-14.csv
site_2-30.csv
site_5-39.csv
site_19-30.csv
site_19-24.csv
site_2-24.csv
site_21-34.csv
site_26-29.csv
site_28-38.csv
site_23-31.csv
site_24-38.csv
site_23-25.csv
site_4-8.csv
site_33-34.csv
site_15-24.csv
site_12-39.csv
site_9-39.csv
site_7-14.csv
site_15-30.csv
site_9-11.csv
site_15-18.csv
site_0-35.csv
site_0-21.csv
site_7-28.csv
site_0-20.csv
site_7-29.csv
site_15-19.csv
site_9-10.csv
site_0-34.csv
site_12-38.csv
site_15-31.csv
site_7-15.csv
site_9-38.csv
site_15-25.csv
site_33-35.csv
site_4-9.csv
site_23-24.csv
site_23-30.csv
site_24-39.csv
site_28-39.csv
site_26-28.csv
site_21-35.csv
site_19-25.csv
site_2-25.csv
site_2-31.csv
site_10-15.csv
site_19-31.csv
site_5-38.csv
site_17-34.csv
site_5-10.csv
site_2-19.csv
site_10-29.csv
site_17-20.csv
site_36-39.csv
site_31-32.csv
site_5-12.csv
site_17-36.csv
site_17-22.csv
site_2-27.csv
site_19-27.csv
site_19-33.csv
site_10-17.csv
site_2-3

In [59]:
csvs = glob.glob(os.path.join(folder, "*.csv"))

In [60]:
for filename in csvs: 
    orthogonal_polynomial(filename, sites=2, dm=4, N=99)

mean
Regression of trait on site 1
[[-2020.90407651   879.96028075 -1353.85036641  3447.14321582]
 [-1815.64268281  8729.11612001 -3018.90143723   431.91097417]]
Regression of trait on site 2
[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

  [[ 2.79642509e+03 -3.69625923e+03  2.75932132e+02 -1.30862503e+03]
   [-2.46956739e+03  1.05122872e+04 -1.41110267e+03 -1.39070283e+03]
   [ 2.70471262e+03 -1.25354686e+04  1.62689861e+03  3.45785717e+03]
   [-4.85806052e+03  1.14934392e+04  2.35771863e+00 -3.00034139e+03]]]


 [[[ 2.79642509e+03 -2.46956739e+03  2.70471262e+03 -4.85806052e+03]
   [-3.69625923e+03  1.05122872e+04 -1.25354686e+04  1.14934392e+04]
   [ 2.75932132e+02 -1.41110267e+03  1.62689861e+03  2.35771863e+00]
   [-1.30862503e+03 -1.39070283e+03  3.4578

Regression of trait on site 1
[[ -803.61378571  3473.75710611 -1810.82892814  1101.26824098]
 [  -43.72318943  3478.89625628 -2521.13039958   223.30870351]]
Regression of trait on site 2
[[[[    0.             0.             0.             0.        ]
   [    0.             0.             0.             0.        ]
   [    0.             0.             0.             0.        ]
   [    0.             0.             0.             0.        ]]

  [[-2859.38991574   162.70017279   707.91260467  1797.92961252]
   [11348.67793176 -5188.48227268 -4245.31205619 -1485.47616567]
   [-2496.70132642 -1336.41647396  2178.57233928   819.50545732]
   [    0.         12326.00186402  -685.98815823 -3199.3438875 ]]]


 [[[-2859.38991574 11348.67793176 -2496.70132642     0.        ]
   [  162.70017279 -5188.48227268 -1336.41647396 12326.00186402]
   [  707.91260467 -4245.31205619  2178.57233928  -685.98815823]
   [ 1797.92961252 -1485.47616567   819.50545732 -3199.3438875 ]]

  [[    0.             0.

Regression of trait on site 1
[[-1382.34138747  2502.94441181  1514.15664502 -1124.91697569]
 [-2377.16507681  5608.31011618 -1874.6835355   1181.81925763]]
Regression of trait on site 2
[[[[     0.              0.              0.              0.        ]
   [     0.              0.              0.              0.        ]
   [     0.              0.              0.              0.        ]
   [     0.              0.              0.              0.        ]]

  [[  -319.59037556 -14252.59520219   2257.68127757   6105.10037641]
   [  4445.03698934  -2463.99473514    208.81585807   -496.78632386]
   [  -794.99444529  24243.65538279  -2891.43297184  -5354.32715101]
   [   183.44733659      0.           1116.51328179  -1217.43336445]]]


 [[[  -319.59037556   4445.03698934   -794.99444529    183.44733659]
   [-14252.59520219  -2463.99473514  24243.65538279      0.        ]
   [  2257.68127757    208.81585807  -2891.43297184   1116.51328179]
   [  6105.10037641   -496.78632386  -5354.32715

KeyboardInterrupt: 