In [1]:
import numpy as np
import glob
import pandas as pd
import json
from matplotlib import pyplot as plt

In [2]:
regressions={}
for file in glob.glob('*.npy'):
    regressions[file] = np.load(file)

In [3]:
#max(x.min(), x.max(), key=abs) https://github.com/numpy/numpy/issues/11622
max_abs_regs = []
max_min_regs = []
site_files={}
new_dict={}

for keys in regressions.keys():
    site_files[keys] = np.load(keys)
    new_dict[keys] = sitbe_files[keys][0][1]
    max_min_regs.append(((site_files[keys][0][1].max()), (site_files[keys][0][1].min())))
    max_abs_regs.append(((max((site_files[keys][0][1].max()), abs((site_files[keys][0][1].min())))))) #this gives abs value of max or min
    print(site_files[keys][0][1])

[[ 2.79642509e+03 -3.69625923e+03  2.75932132e+02 -1.30862503e+03]
 [-2.46956739e+03  1.05122872e+04 -1.41110267e+03 -1.39070283e+03]
 [ 2.70471262e+03 -1.25354686e+04  1.62689861e+03  3.45785717e+03]
 [-4.85806052e+03  1.14934392e+04  2.35771863e+00 -3.00034139e+03]]
[[ 2474.67819025  3352.45113053 -3074.22332209   169.89042357]
 [  739.10872533 11603.78617936 -1943.14676203 -2686.13271964]
 [  -42.4100991  -5327.80152049  1394.92598951  1365.73366803]
 [-1370.51832147 -5783.13369599  2816.82869829   -66.46344404]]
[[ 3438.90218411   462.13295264  1777.39033501 -3246.11771957]
 [  -85.6775488  -1402.78767534  1013.07361849   213.77568426]
 [-1084.77239872  3855.78605026 -3696.90950175  3818.78953014]
 [-2193.39486956 -4441.75767994  2464.28954956   821.56106058]]
[[ 1156.70207086 -1747.58862497  2041.98909099 -1349.53358889]
 [-5115.1693399  11300.48180301 -4787.83544269  2390.71908158]
 [ 1971.81484399 -3360.82425149  1350.60377921  -797.14731082]
 [-1292.17648521 -3853.2353695   -73

[[ 1640.78293801  -696.83406195  3441.21744276 -5190.41926325]
 [  877.55066398 -3032.51527184     0.           207.66553342]
 [  315.39290521 -1221.34141987  2183.02239328 -4375.28701462]
 [-2438.5037716  -1856.02668578 -4546.48005736  6019.09296636]]
[[-1029.65854364  1074.6510567   -678.573956    1315.46687468]
 [    0.          -430.3656377    322.96852901    69.59972268]
 [ 2365.21687502 -3126.16843118  1119.4754938  -1611.77934066]
 [ 1106.34221977     0.         -1239.81109089   497.60650731]]
[[-2342.14460987  3245.88593237 -2306.90518943  2575.26005108]
 [ 7877.14938012 -7048.36916672  2870.63554989 -5281.77190308]
 [  -80.51053963  -584.30559563  1573.24489427 -1435.39555343]
 [ -334.48022193   500.78173192   137.56252158   -62.26366613]]
[[ 2674.71640425  3103.5236483  -1570.68071872 -2307.43104484]
 [-4313.19593314 -5823.624553   -6613.98845056 14912.05446896]
 [ 1771.72059067  -446.99969287  2024.10554272 -3757.92819687]
 [-1538.56157804 -1402.34944527  3736.05589313 -2208

[[  731.00541702 -5745.53338275   737.08656959   567.04627499]
 [  423.71591407 -5133.95294716  7509.46270207 -3819.35747277]
 [ -781.40699829  1306.28189564 -3985.59838819  4862.61696272]
 [ -518.32418398  4728.63758842  1987.53836487 -3994.93314821]]
[[ 2123.70876315   812.22555012 -1671.6050387  -1993.78069804]
 [-1287.39372139  6431.95800133  4079.71250301 -7547.02107624]
 [ 1731.19573538 -1955.58709548    77.50909547 -1165.59536742]
 [-2377.65902211 -7361.25684584    55.23021268  5011.52276319]]
[[  198.1377124  -3777.95873646  2049.3327323  -1512.43160228]
 [-3110.45789552     0.         -1650.53751485  2736.08075752]
 [  112.56104046 -4063.34344269  1523.6336946    632.82190676]
 [  825.81087942  1094.29936463 -2990.45271348  1641.73630172]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 1284.28547272  2584.17188284  1251.2435983  -3307.96728901]
 [-2733.99772017 -8261.86791705 -2394.33423805  8328.35467445]
 [ 1278.06595204 -3701.02277875  -126.23165409  -298.4

In [109]:
#max(x.min(), x.max(), key=abs) https://github.com/numpy/numpy/issues/11622
max_abs_ind = []
site_files={}
new_dict={}

for keys in regressions.keys():
    site_files[keys] = np.load(keys)
    new_dict[keys] = site_files[keys][0][1]
    #max_abs_ind.append(((np.argmax((site_files[keys][0][1].max()), abs((site_files[keys][0][1].min())))))) 
    max_abs_ind.append( np.unravel_index( np.abs( new_dict[keys] ).argmax(), new_dict[keys].shape) ) 

In [110]:
max_abs_ind

[(2, 1),
 (1, 1),
 (3, 1),
 (1, 1),
 (1, 1),
 (2, 3),
 (3, 1),
 (0, 1),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 0),
 (0, 3),
 (1, 3),
 (3, 1),
 (1, 3),
 (3, 1),
 (1, 3),
 (1, 0),
 (3, 1),
 (1, 3),
 (3, 0),
 (0, 3),
 (2, 3),
 (3, 0),
 (0, 1),
 (0, 0),
 (0, 3),
 (3, 1),
 (1, 0),
 (1, 0),
 (3, 0),
 (1, 1),
 (0, 1),
 (1, 3),
 (2, 3),
 (1, 3),
 (2, 1),
 (2, 3),
 (0, 1),
 (1, 2),
 (1, 2),
 (0, 1),
 (0, 1),
 (1, 0),
 (2, 1),
 (0, 0),
 (3, 3),
 (3, 3),
 (2, 3),
 (2, 3),
 (1, 3),
 (2, 3),
 (0, 1),
 (1, 1),
 (1, 3),
 (1, 3),
 (0, 1),
 (1, 3),
 (0, 1),
 (1, 2),
 (1, 1),
 (1, 1),
 (3, 1),
 (3, 0),
 (1, 0),
 (3, 1),
 (1, 1),
 (0, 1),
 (1, 0),
 (1, 3),
 (3, 0),
 (1, 0),
 (1, 2),
 (1, 1),
 (0, 3),
 (1, 1),
 (3, 0),
 (1, 0),
 (3, 1),
 (1, 3),
 (1, 1),
 (1, 1),
 (2, 3),
 (1, 3),
 (1, 1),
 (1, 1),
 (1, 3),
 (1, 1),
 (1, 1),
 (0, 1),
 (1, 0),
 (0, 1),
 (1, 0),
 (0, 1),
 (3, 1),
 (0, 1),
 (3, 2),
 (1, 3),
 (0, 1),
 (0, 1),
 (3, 1),
 (2, 1),
 (0, 1),
 (1, 1),
 (3, 1),
 (2, 1),
 (2, 1),
 (1, 3),
 (3, 1),
 (3, 0),
 

In [56]:
max_min_regs

[(11493.439217272611, -12535.468564594757),
 (11603.786179364835, -5783.133695988294),
 (3855.7860502584685, -4441.757679944121),
 (11300.4818030098, -5115.169339904468),
 (17289.132226326383, -4665.426299318021),
 (14716.737258096748, -6693.729313454058),
 (5436.85944515454, -8829.609697844866),
 (5436.610426002147, -18807.25652121924),
 (11142.464699620725, -6492.452133330947),
 (9919.531083473585, -5995.940560075292),
 (15539.32677398906, -9851.026089992396),
 (17585.134620337398, -11313.130442622838),
 (8426.294524137853, -6318.193821114537),
 (9565.462129524456, -7792.486029067858),
 (12351.7681542688, -5516.10410301316),
 (12961.996980849754, -7457.13921028203),
 (7663.649620997136, -6481.772605955852),
 (5882.237812741406, -5140.298639033121),
 (6315.329710131204, -5410.351583890209),
 (8411.155894436506, -7786.846434460605),
 (5100.194475976895, -4659.9893591813925),
 (7011.672372312375, -6391.096216583682),
 (10124.3753858696, -4340.615460424794),
 (3845.265973482996, -4836.96

In [55]:
max_abs_regs

[12535.468564594757,
 11603.786179364835,
 4441.757679944121,
 11300.4818030098,
 17289.132226326383,
 14716.737258096748,
 8829.609697844866,
 18807.25652121924,
 11142.464699620725,
 9919.531083473585,
 15539.32677398906,
 17585.134620337398,
 8426.294524137853,
 9565.462129524456,
 12351.7681542688,
 12961.996980849754,
 7663.649620997136,
 5882.237812741406,
 6315.329710131204,
 8411.155894436506,
 5100.194475976895,
 7011.672372312375,
 10124.3753858696,
 4836.965397750264,
 19911.28332939426,
 15464.432569046288,
 0.0,
 6410.210874392538,
 17655.08653336479,
 8299.256530704886,
 8550.453058113859,
 20632.78156191335,
 9182.424322817975,
 7072.138827925853,
 6612.648911197284,
 14246.980381846688,
 12267.8852585826,
 11270.924128061177,
 6082.211377624451,
 5999.323821525533,
 5483.740128554959,
 15170.162422770847,
 40675.03313025431,
 14508.591503477697,
 9704.9535691954,
 7075.619561133522,
 16484.008279789276,
 6658.82956260187,
 3175.4421774823245,
 8138.873380859767,
 5944.0

In [57]:
df_max_abs_regs = pd.DataFrame(dict(pair = list(site_files.keys()), max_reg_val = max_abs_regs))

In [58]:
df_max_abs_regs

pair   max_reg_val
0    site_36-38.csv.npy  12535.468565
1      site_4-9.csv.npy  11603.786179
2    site_11-37.csv.npy   4441.757680
3     site_2-23.csv.npy  11300.481803
4    site_11-27.csv.npy  17289.132226
..                  ...           ...
775  site_14-23.csv.npy  11681.074672
776   site_7-37.csv.npy   9974.131920
777   site_5-12.csv.npy   7274.315062
778    site_7-8.csv.npy   5073.336456
779  site_23-33.csv.npy   6489.876235

[780 rows x 2 columns]

In [4]:
max_regs_only=[]
for keys in regressions.keys():
    site_files[keys] = np.load(keys)
    max_regs_only.append(site_files[keys][0][1].max()) if site_files[keys][0][1].max() > abs(site_files[keys][0][1].min()) else max_regs_only.append(site_files[keys][0][1].min())

In [5]:
max_regs_only

[-12535.468564594757,
 11603.786179364835,
 -4441.757679944121,
 11300.4818030098,
 17289.132226326383,
 14716.737258096748,
 -8829.609697844866,
 -18807.25652121924,
 11142.464699620725,
 9919.531083473585,
 15539.32677398906,
 17585.134620337398,
 8426.294524137853,
 9565.462129524456,
 12351.7681542688,
 12961.996980849754,
 7663.649620997136,
 5882.237812741406,
 6315.329710131204,
 8411.155894436506,
 5100.194475976895,
 7011.672372312375,
 10124.3753858696,
 -4836.965397750264,
 19911.28332939426,
 -15464.432569046288,
 0.0,
 6410.210874392538,
 17655.08653336479,
 8299.256530704886,
 -8550.453058113859,
 20632.78156191335,
 -9182.424322817975,
 7072.138827925853,
 6612.648911197284,
 14246.980381846688,
 12267.8852585826,
 11270.924128061177,
 -6082.211377624451,
 5999.323821525533,
 -5483.740128554959,
 15170.162422770847,
 40675.03313025431,
 14508.591503477697,
 9704.9535691954,
 -7075.619561133522,
 16484.008279789276,
 -6658.82956260187,
 -3175.4421774823245,
 8138.87338085

In [8]:
test_d=new_dict['site_36-38.csv.npy']

In [9]:
np.argwhere(test_d == max_regs_only[0]) #this corresponds to the value -12535.46 in the 1st mtx 

array([[2, 1]])

In [10]:
test_2=new_dict['site_11-37.csv.npy']

In [11]:
np.argwhere(test_2 == max_regs_only[2]) #this corresponds to the value -4441.75 in the 3rd mtx #yay

array([[3, 1]])

In [36]:
np.unravel_index(np.argmin(test_d, axis=None), test_d.shape) #argmin

(2, 1)

In [37]:
np.unravel_index(np.argmax(test_d, axis=None), test_d.shape)

(3, 1)

In [40]:
np.argmax((np.argmax(test_d, axis=None),abs(np.argmin(test_d, axis=None))), axis=None)

0

In [44]:
max((np.argmax(test_d, axis=None),abs(np.argmin(test_d, axis=None))))

13

In [47]:
test_d.max()

11493.439217272611

In [48]:
test_d.min()

-12535.468564594757

In [50]:
(max((test_d.max()), abs((test_d.min()))))

12535.468564594757

In [53]:
np.argwhere((max((test_d.max()), abs((test_d.min())))))

array([[0]])

In [54]:
np.unravel_index((max((test_d.max()), abs((test_d.min())))),test_d.shape)

TypeError: Iterator operand 0 dtype could not be cast from dtype('float64') to dtype('int64') according to the rule 'same_kind'

In [42]:
np.unravel_index(max((np.argmax(test_d, axis=None),abs(np.argmin(test_d, axis=None)))), test_d.shape)

(3, 1)

In [100]:
test_d.tolist().index((max((test_d.max()), abs((test_d.min())))).all())

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [92]:
#test_d.tolist() # Python list
max_val = max((test_d.max()), abs((test_d.min())))
i = test_d.tolist().index((max_val).any())
print(i)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [74]:
print(test_d[0],test_d[1],test_d[2],test_d[3])
print(test_d[2][1])

[ 2796.42508857 -3696.25922819   275.93213189 -1308.62502738] [-2469.56738749 10512.28715457 -1411.10267469 -1390.70283418] [  2704.71262268 -12535.46856459   1626.8986082    3457.85717279] [-4.85806052e+03  1.14934392e+04  2.35771863e+00 -3.00034139e+03]
-12535.468564594757


In [80]:
print(test_d.shape[0])
print(test_d.shape[1])

4
4


In [86]:
indices = []
for i in range(test_d.shape[0]):
    for j in range(test_d.shape[1]):
        if j>>i:
            if test_d[i][j] == max((test_d.max()), abs((test_d.min()))):
                indices.append((i, j, max((test_d.max()), abs((test_d.min())))))
                print(indices)
print(len(indices))

0


In [18]:
len(new_dict)

780

In [28]:
for i in range(len(max_regs_only)):
    for keys in new_dict.keys():
        #print(np.argwhere(new_dict[keys] == max_regs_only[i]))
        continue
    print(np.argwhere(new_dict[keys] == max_regs_only[i]))

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[2 1]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[2 1]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[2 1]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[2 1]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[2 1]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]


In [32]:
for keys in new_dict.keys():
    for i in range(len(max_regs_only)):
        for j in range(len(new_dict)):
            while i < j:
                print(np.argwhere(new_dict[keys] == max_regs_only[i]))
        

[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]
[[2 1]]


KeyboardInterrupt: 

In [6]:
#need to get the indices of the max_regs_only values!!
#max_reg_indices=[]
max_reg_indices=np.empty((0, 2),float)
for keys in regressions.keys():
    site_files[keys] = np.load(keys)
    new_dict[keys] = site_files[keys][0][1]
    arr = np.argwhere(new_dict[keys] == max_regs_only[i] for i in range(len(max_regs_only)))
    max_reg_indices=np.append(max_reg_indices, [arr], axis=0)

ValueError: all the input arrays must have same number of dimensions